### ISSUE TITLE
Failing Tests (automated + visual) that previously passed

### ISSUE THREAD

**Issue by Lemmart** [Lemmart/food-blog-1#1]
**Code coverage prior to push: 95%
Code coverage after push: 80%**

**Comments UI**: appends "2: " to new comments when username should be displayed - this is not reflected/caught within any tests (should be developed as features are rolled out)

**Create Post test** - web steps and associated tests that previously were passing are currently failing
**Review**: 2 tests (testing for presence of image) are expected to fail; all other tests should pass (via cucumber + rspec)

**Comment by lhenske** [comment]
This testing issue was resolved Tuesday night 4/17
